### ISSUE TITLE
Unsoundness: `DefaultBoxed` should be marked an `unsafe trait`

### ISSUE THREAD

**Issue by SabrinaJewson** [upsuper/default-boxed#8]
Example of reading an uninitialized `u8` with no `unsafe` code:

```rs
struct Helper(u8);

impl DefaultBoxed for Helper {
    // Defining an unsafe function with no unsafe operations does not count as `unsafe`
    unsafe fn default_in_place(ptr: *mut Self) {}
}

fn main() {
    println!("{}", Helper::default_boxed().0);
}
```

**Comment by upsuper** [comment]
Thanks for reporting.

I guess that means the trait should be marked `unsafe` itself with a safety section saying the `default_in_place` must initialize the object the pointer points to properly.
